version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building static files..."
  post_build:
    commands:
      - aws s3 sync ./dist s3://testingernestbucket/
